=== tommc/lindbergframework/trunk/_FONTES/lindbergframework/src/main/java/org/lindbergframework/schemas/linp-sqlMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.lindbergframework.org/schema" 
        xmlns="http://www.lindbergframework.org/schema" 
        elementFormDefault="qualified">
        
    <!-- autor: Victor Lindberg -->
    
    <xs:annotation>
		<xs:documentation>
		    Lindberg XML sql mapping schema version 1.0. Author: Victor Lindberg.
	    </xs:documentation>
	</xs:annotation>
	
	<xs:element name="Linp-Mapping">
	    <xs:annotation>
			   <xs:documentation>Root element of the schema</xs:documentation>
		</xs:annotation>
        <xs:complexType>
           <xs:all>
              <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="Sql-Mapping" minOccurs="0" maxOccurs="1">
                 <xs:complexType>
                    <xs:sequence>
                       <xs:element name="Sql-Command" type="tSql-Command" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                 </xs:complexType>
              </xs:element>
           </xs:all>
        </xs:complexType>
    </xs:element>
	
	<!-- Complex Types -->
	<xs:complexType name="tOutCursor" >
        <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>
    
	<xs:complexType name="tFunctionResultCursor" >
        <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="tProcedure" >
        <xs:sequence>
		   <xs:element name="OutCursor" type="tOutCursor" minOccurs="0" maxOccurs="unbounded"/>   
        </xs:sequence> 
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="schema" type="xs:string" />
        <xs:attribute name="package" type="xs:string" />
        <xs:attribute name="catalog" type="xs:string" />
    </xs:complexType>
    
	<xs:complexType name="tFunction" >
	    <xs:complexContent>
           <xs:extension base="tProcedure">
              <xs:sequence>
                 <xs:element name="ResultCursor" type="tFunctionResultCursor" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:attribute name="resultName" type="xs:string" />
           </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="tSql-Command" >
        <xs:choice>
           <xs:element name="Sql-Statement" type="xs:string" />
           <xs:element name="Procedure" type="tProcedure" />
           <xs:element name="Function" type="tFunction" />
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
	
</xs:schema>

=== tommc/lindbergframework/trunk/_FONTES/lindbergframework/src/test/resources/org/lindbergframework/test/persistence/resource/oracle/Updates.xml
<?xml version="1.0" encoding="UTF-8"?>
<Linp-Mapping xmlns="http://www.lindbergframework.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lindbergframework.org/schema ../org/lindbergframework/schemas/linp-sqlMapping.xsd ">

    <Description>Updates</Description>
    
    <Sql-Mapping>
       <Sql-Command id="updatePersonpNicknameAndProfession">
          <Sql-Statement>
              update person set nickname = ?, profession = ? where id = ?
          </Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="insertPerson">
          <Sql-Statement>insert into person(id,nickname,profession,street,addres_num,birth_date) values(?,?,?,?,?,?)</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="deletePerson">
          <Sql-Statement>delete from person where id = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="updatePersonNickNameBirthDateProcedure">
          <Procedure name="updatePersonNicknameBirthdate" />
       </Sql-Command>
       
       <Sql-Command id="updatePersonNickBirthDateFunction">
          <Function name="updatePersonNickBirthdateFunc" />
       </Sql-Command>
       
       <Sql-Command id="simpleProcedure">
          <Procedure name="simpleProcedure" />
       </Sql-Command>
    </Sql-Mapping>          

</Linp-Mapping>

=== tommc/lindbergframework/trunk/_FONTES/lindbergframework/src/test/resources/org/lindbergframework/test/persistence/resource/oracle/Queries.xml
<?xml version="1.0" encoding="UTF-8"?>
<Linp-Mapping xmlns="http://www.lindbergframework.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lindbergframework.org/schema ../org/lindbergframework/schemas/linp-sqlMapping.xsd ">

    <Description>Queries</Description>
    
    <Sql-Mapping>
       <Sql-Command id="queryPersons">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsLikeNickname">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where nickname like ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsFromId">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where id = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsFromBirth_date">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where birth_date = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryEmployees">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number, 1000 wage from person p</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsFromProcedure">
          <Procedure name="listPersonsLikeNickName" >
             <OutCursor population-class="org.lindbergframework.test.testBeans.Person"/>
          </Procedure>
       </Sql-Command>
              
       <Sql-Command id="queryOut3PersonsFromProcedure">
          <Procedure name="out3Persons" >
             <OutCursor population-class="org.lindbergframework.test.testBeans.Person"/>
             <OutCursor population-class="org.lindbergframework.test.testBeans.Person"/>
             <OutCursor population-class="org.lindbergframework.test.testBeans.Person"/>
          </Procedure>
       </Sql-Command>  
       
       <Sql-Command id="queryPersonsFromFunction">
          <Function name="listPersonsLikeNickNameFunc" resultName="personsList">
             <ResultCursor population-class="org.lindbergframework.test.testBeans.Person" />
          </Function>
       </Sql-Command>
              
    </Sql-Mapping>          

</Linp-Mapping>

=== tommc/lindbergframework/trunk/_EXEMPLOS/ExemploLinp/src/org/lindbergframework/exemplo/sql/exemploUpdates.xml
<?xml version="1.0" encoding="UTF-8"?>
<Linp-Mapping xmlns="http://www.lindbergframework.org/schema" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.lindbergframework.org/schema linp-sqlMapping.xsd">
		
<Description>Exemplo de Updates</Description>
    
    <Sql-Mapping>
       <Sql-Command id="inserirPessoa">
          <Sql-Statement>insert into pessoa values(?,?,?,?,?,?)</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="excluirPessoa">
          <Sql-Statement>delete from pessoa where cpf = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="atualizarEnderecoPessoa">
          <Sql-Statement>update pessoa set bairro = ?, rua = ?, numero = ?, numeroCep = ? where cpf = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="excluirPessoaUsandoProcedure">
          <Procedure name="excluirPessoa"/>
       </Sql-Command>
       
       <Sql-Command id="excPessoasPorIniciaisRetornandoExcluidosENaoExcluidosUsandoFunction">
          <Function name="excPessoasRetornaExcluidosFunc" resultName="pessoasexcluidas">
             <OutCursor population-class="org.lindbergframework.exemplo.beans.Pessoa"/><!-- Não Excluidos São como resultado da função através de um cursor  -->
             <ResultCursor population-class="org.lindbergframework.exemplo.beans.Pessoa" /><!-- Excluidos -->
          </Function>
       </Sql-Command>
       
       <Sql-Command id="excPessoasPorIniciaisRetornandoExcluidosENaoExcluidosUsandoProcedure">
          <Procedure name="excPessoasRetornaExcluidosProc">
             <OutCursor population-class="org.lindbergframework.exemplo.beans.Pessoa"/><!-- Não Excluidos -->
             <OutCursor population-class="org.lindbergframework.exemplo.beans.Pessoa"/><!-- Excluidos -->
          </Procedure>
       </Sql-Command>
    </Sql-Mapping>
    		
</Linp-Mapping>

=== tommc/lindbergframework/trunk/_FONTES/lindbergframework/src/test/resources/org/lindbergframework/test/persistence/resource/mysql/Queries.xml
<?xml version="1.0" encoding="UTF-8"?>
<Linp-Mapping xmlns="http://www.lindbergframework.org/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lindbergframework.org/schema ../org/lindbergframework/schemas/linp-sqlMapping.xsd ">

    <Description>Queries</Description>
    
    <Sql-Mapping>
       <Sql-Command id="queryPersons">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsLikeNickname">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where nickname like ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsFromId">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where id = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryPersonsFromBirth_date">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number from person p where birth_date = ?</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="queryEmployees">
          <Sql-Statement>select p.*,street addres.street, addres_num addres.number, 1000 wage from person p</Sql-Statement>
       </Sql-Command>
       
       <Sql-Command id="findPersonNickFromProcedure">
          <Procedure name="findPerson" />
       </Sql-Command>
                
       <Sql-Command id="out3NickPersons">
          <Procedure name="out3NickPersons" />
       </Sql-Command>
                
       <Sql-Command id="findPersonNickFunc">
          <Function name="findPersonNickFunc" />
       </Sql-Command>
       
    </Sql-Mapping>          

</Linp-Mapping>
